### ISSUE TITLE
AssertionError: Start canary of block corrupted.

### ISSUE THREAD

**Issue by NicolasDumoulin** [tdihp/osrm-c#2]
Me again :-)

I'm trying to use your python bindings, and am stucked on trying to initialize an OSRM instance. My script:

```
from osrm import OSRM
osrm = OSRM("../build/libosrm_c.so.0.2.0")
```

And I get this error:

```
~/osrm-c/example$ python test_query.py 
Traceback (most recent call last):
  File "test_query.py", line 3, in <module>
    osrm = OSRM("../build/libosrm_c.so.0.2.0")
  File "/home/user/osrm-c/example/osrm.py", line 101, in __init__
    assert errptr[0] == ffi.NULL, ffi.string(errptr[0])
AssertionError: Start canary of block corrupted.
Erreur de segmentation (core dumped)
```

And I don't understand this error.

**Comment by tdihp** [comment]
Hi, my python OSRM implimentation will try to use [shared memory](https://github.com/Project-OSRM/osrm-backend/wiki/Configuring-and-using-Shared-Memory#using-shared-memory) feature of OSRM, if base path of data is not provided.

The exception here is a OSRM backend (C++) init failure, possibly because the shared memory is not correctly set. Have you run `./osrm-datastore /path/to/data.osrm` before running this script?

**Comment by NicolasDumoulin** [comment]
Ok. Now it works!
Thanks
